site_name: netLD/ThirdEye SDK
pages:
- API Overview: Welcome.md
- Inventory: Inventory.md
- Networks: Networks.md
- Jumphosts: Jumphost.md
- Configuration: Configuration.md
- Credentials: Credentials.md
- Scheduler: Scheduler.md
- Plugins: Plugins.md
- Compliance: Compliance.md
- Telemetry: Telemetry.md
- Terminal Proxy: TerminalProxy.md
- Bridges: Bridges.md
- ZeroTouch: ZeroTouch.md
- Incidents: Incidents.md
- Appendix A: Appendix_A.md
theme: readthedocs
