site_name: netLD SDK
pages:
- API Overview: Welcome.md
- Inventory: Inventory.md
- Configuration: Configuration.md
- Credentials: Credentials.md
- Scheduler: Scheduler.md
- Plugins: Plugins.md
- Compliance: Compliance.md
- Appendix A: Appendix_A.md
theme: readthedocs
